DECLARE @UserId NVARCHAR(64) = N'__APP_DB_USER__';

DELETE FROM dbo.ASSETACCESS
WHERE USER_ID = @UserId;

INSERT INTO dbo.ASSETACCESS (ID, USER_ID, ASSET_ID)
VALUES
    (CONVERT(NVARCHAR(64), NEWID()), @UserId, N'__ASSET_ID_1__');

-- Add more allowed assets as needed:
-- INSERT INTO dbo.ASSETACCESS (ID, USER_ID, ASSET_ID)
-- VALUES (CONVERT(NVARCHAR(64), NEWID()), @UserId, N'__ASSET_ID_2__');
